{
parserClass="org.ca65.AsmParser"

extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

psiClassPrefix="Asm"
psiImplClassSuffix="Impl"
psiPackage="org.ca65.psi"
psiImplPackage="org.ca65.psi.impl"

elementTypeHolderClass="org.ca65.psi.AsmTypes"
elementTypeClass="org.ca65.psi.AsmElementType"
tokenTypeClass="org.ca65.psi.AsmTokenType"
psiImplUtilClass="org.ca65.psi.impl.AsmPsiImplUtil"
implements("marker")="com.intellij.psi.PsiNamedElement"
implements("identifierdef")="com.intellij.psi.PsiNamedElement"
}


asmFile ::= item_* last_line?

private item_ ::= marker? (dotexpr|register_dotexpr|imports|define_constant_label|define_constant_numeric|enum_def|struct_def|union_def|scope_def|proc_def|macro|llabel|star_assign)? COMMENT? EOL_WS

// repeat of above, to handle files that do not end with a newline
private last_line ::= marker? (dotexpr|register_dotexpr|imports|define_constant_label|define_constant_numeric|enum_def|struct_def|union_def|scope_def|proc_def|macro|llabel|star_assign)? COMMENT?

marker ::= (LABEL | SHORTLABEL) {
    mixin="org.ca65.psi.impl.AsmLabelDefinitionImpl"
    methods=[getLabelName getPresentation getName setName getNameIdentifier]
}

identifierdef ::= identifierr {
    mixin="org.ca65.psi.impl.AsmIdentifierDefinitionImpl"
    methods=[getLabelName getPresentation getName setName getNameIdentifier]
}
imports ::= IMPORT_KEYWORD identifierdef ( COMMA identifierdef )*
dotexpr ::= DOT_KEYWORD expr {
    mixin="org.ca65.psi.impl.AsmDotexprMixin"
}
register_dotexpr ::= REGISTER_DOT_KEYWORD
macro ::= IDENTIFIER expr
llabel ::=  instruction_mnemonic expr?

define_constant_numeric ::= identifierdef ( EQUALS ) expr
define_constant_label ::= identifierdef ( COLON_EQUALS ) expr
star_assign ::= MUL EQUALS expr

// .enum NAME / .endenum blocks
enum_def ::= ENUM_KEYWORD identifierdef? COMMENT? EOL_WS enum_body ENDENUM_KEYWORD {
    mixin="org.ca65.psi.impl.AsmEnumDefMixin"
    methods=[getName getPresentation getNameIdentifier setName getEnumMemberList]
}

private enum_body ::= enum_body_line*

private enum_body_line ::= enum_member COMMENT? EOL_WS
                          | COMMENT? EOL_WS

enum_member ::= identifierdef (EQUALS expr)? {
    mixin="org.ca65.psi.impl.AsmEnumMemberMixin"
    methods=[getName getPresentation getNameIdentifier setName getComputedValue]
}

// .struct NAME / .endstruct and .union NAME / .endunion blocks
struct_def ::= STRUCT_KEYWORD identifierdef? COMMENT? EOL_WS struct_body ENDSTRUCT_KEYWORD {
    mixin="org.ca65.psi.impl.AsmStructDefMixin"
    methods=[getName getPresentation getNameIdentifier setName getStructMemberList]
}

union_def ::= UNION_KEYWORD identifierdef? COMMENT? EOL_WS struct_body ENDUNION_KEYWORD {
    mixin="org.ca65.psi.impl.AsmStructDefMixin"
    methods=[getName getPresentation getNameIdentifier setName getStructMemberList]
}

private struct_body ::= struct_body_line*

private struct_body_line ::= struct_member COMMENT? EOL_WS
                            | DOT_KEYWORD expr? COMMENT? EOL_WS
                            | STRUCT_KEYWORD IDENTIFIER? COMMENT? EOL_WS struct_body ENDSTRUCT_KEYWORD COMMENT? EOL_WS
                            | UNION_KEYWORD IDENTIFIER? COMMENT? EOL_WS struct_body ENDUNION_KEYWORD COMMENT? EOL_WS
                            | COMMENT? EOL_WS

struct_member ::= IDENTIFIER DOT_KEYWORD expr? {
    mixin="org.ca65.psi.impl.AsmStructMemberMixin"
    methods=[getName getPresentation getNameIdentifier setName]
}

// .scope NAME / .endscope blocks
scope_def ::= SCOPE_KEYWORD identifierdef? COMMENT? EOL_WS item_* ENDSCOPE_KEYWORD {
    mixin="org.ca65.psi.impl.AsmScopeDefMixin"
    methods=[getName getPresentation getNameIdentifier setName]
}

// .proc NAME / .endproc blocks
proc_def ::= PROC_KEYWORD marker? identifierdef? expr? COMMENT? EOL_WS item_* ENDPROC_KEYWORD {
    mixin="org.ca65.psi.impl.AsmProcDefMixin"
    methods=[getLabelName getName getPresentation getNameIdentifier setName]
}

expr ::= anything*

anything ::= (instruction_mnemonic|numeric_literal|STRING_LITERAL|DOT_KEYWORD|REGISTER_DOT_KEYWORD|identifierr|LABEL|EQUALS|COLON_EQUALS|COMMA|REGISTER|CHAR_LITERAL|LPAREN|RPAREN|LSQUAREBRACKET|RSQUAREBRACKET|OR|LSHIFT|RSHIFT|AND|CONSTEXPR|SHORTLABEL_REF|local_label_rref|SHORTLABEL|HIBYTE|LOBYTE|BOOLOR|BOOLAND|NOT|DIV|MUL|ADD|SUB|XOR|SCOPE_ACCESS|LE|GE|NE|BOOLNOT|LCURLY|RCURLY)

numeric_literal ::= INT_LITERAL
instruction_mnemonic ::= MNEMONIC

identifierr ::= IDENTIFIER | MNEMONIC {
    mixin="org.ca65.psi.impl.AsmIdentifierImpl"
    methods=[getName]
}

local_label_rref ::= LOCAL_LABEL_REF {
    mixin="org.ca65.psi.impl.AsmLocalLabelRefImpl"
    methods=[getName]
}

// Just to define the symbols
also ::= (LINE_WS|EOL_WS|ENUM_KEYWORD|ENDENUM_KEYWORD|STRUCT_KEYWORD|ENDSTRUCT_KEYWORD|UNION_KEYWORD|ENDUNION_KEYWORD|SCOPE_KEYWORD|ENDSCOPE_KEYWORD|PROC_KEYWORD|ENDPROC_KEYWORD)
